CREATE PROCEDURE [dbo].[uspGetAllUserBellingAddress]
	AS
	BEGIN
			SELECT 
			Id,
			UserId,
			AddessLineOne,
			AddessLineTwo,
			AddessLineThress,
			Location,
			CountryId,
			StateId,
			CityId,
			PinCode,
			CreatedBy,
			CreatedOn,
			ModifiedBy,
			ModifiedOn,
			IsActive
			from 
			[dbo].[UserBillingAddress]
	END
